
# This file is automatically generated, you probably don't want to edit this

complex2longOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "complex2longOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            colstorows = list(
                list(label="long_y", vars=list())),
            covs = NULL,
            index = list(
                list(var="index1", levels=0)),
            filename = "longdata.csv",
            open = TRUE,
            button = NULL,
            create = FALSE,
            toggle = FALSE, ...) {

            super$initialize(
                package="jReshape",
                name="complex2long",
                requiresData=TRUE,
                ...)

            private$..colstorows <- jmvcore::OptionArray$new(
                "colstorows",
                colstorows,
                default=list(
                    list(label="long_y", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "colstorows",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL))))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs)
            private$..index <- jmvcore::OptionArray$new(
                "index",
                index,
                default=list(
                    list(var="index1", levels=0)),
                template=jmvcore::OptionGroup$new(
                    "index",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL),
                        jmvcore::OptionInteger$new(
                            "levels",
                            NULL))))
            private$..filename <- jmvcore::OptionString$new(
                "filename",
                filename,
                default="longdata.csv")
            private$..open <- jmvcore::OptionBool$new(
                "open",
                open,
                default=TRUE)
            private$..button <- jmvcore::OptionString$new(
                "button",
                button,
                hidden=TRUE)
            private$..create <- jmvcore::OptionBool$new(
                "create",
                create,
                default=FALSE,
                hidden=TRUE)
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                default=FALSE,
                hidden=TRUE)

            self$.addOption(private$..colstorows)
            self$.addOption(private$..covs)
            self$.addOption(private$..index)
            self$.addOption(private$..filename)
            self$.addOption(private$..open)
            self$.addOption(private$..button)
            self$.addOption(private$..create)
            self$.addOption(private$..toggle)
        }),
    active = list(
        colstorows = function() private$..colstorows$value,
        covs = function() private$..covs$value,
        index = function() private$..index$value,
        filename = function() private$..filename$value,
        open = function() private$..open$value,
        button = function() private$..button$value,
        create = function() private$..create$value,
        toggle = function() private$..toggle$value),
    private = list(
        ..colstorows = NA,
        ..covs = NA,
        ..index = NA,
        ..filename = NA,
        ..open = NA,
        ..button = NA,
        ..create = NA,
        ..toggle = NA)
)

complex2longResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "complex2longResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        save = function() private$.items[["save"]],
        info = function() private$.items[["info"]],
        features = function() private$.items[["features"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Wide to Long format (complex)")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                title="Getting started"))
            self$add(jmvcore::Table$new(
                options=options,
                name="save",
                title="The new data file info",
                columns=list(
                    list(
                        `name`="text", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="info", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                clearWith=NULL,
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="Repeated measures levels",
                columns=list(
                    list(
                        `name`="Freq", 
                        `title`="Freq", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

complex2longBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "complex2longBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReshape",
                name = "complex2long",
                version = c(1,0,0),
                options = options,
                results = complex2longResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Wide to Long format (complex)
#'
#' 
#' @param data .
#' @param colstorows .
#' @param covs .
#' @param index .
#' @param filename .
#' @param open .
#' @param button .
#' @param create .
#' @param toggle .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$save} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$save$asDF}
#'
#' \code{as.data.frame(results$save)}
#'
#' @export
complex2long <- function(
    data,
    colstorows = list(
                list(label="long_y", vars=list())),
    covs,
    index = list(
                list(var="index1", levels=0)),
    filename = "longdata.csv",
    open = TRUE,
    button,
    create = FALSE,
    toggle = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("complex2long requires jmvcore to be installed (restart may be required)")

    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(covs), covs, NULL))


    options <- complex2longOptions$new(
        colstorows = colstorows,
        covs = covs,
        index = index,
        filename = filename,
        open = open,
        button = button,
        create = create,
        toggle = toggle)

    analysis <- complex2longClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

