
# This file is automatically generated, you probably don't want to edit this

jrmergecolsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varBy = NULL,
            varAll = NULL,
            fleInp = "",
            fleChs = "",
            typMrg = "outer",
            btnRes = FALSE, ...) {

            super$initialize(
                package="jReshape",
                name="jrmergecols",
                requiresData=TRUE,
                ...)

            private$..varBy <- jmvcore::OptionVariables$new(
                "varBy",
                varBy,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..fleInp <- jmvcore::OptionString$new(
                "fleInp",
                fleInp,
                default="")
            private$..fleChs <- jmvcore::OptionString$new(
                "fleChs",
                fleChs,
                hidden=TRUE,
                default="")
            private$..typMrg <- jmvcore::OptionList$new(
                "typMrg",
                typMrg,
                options=list(
                    "outer",
                    "inner",
                    "left",
                    "right"),
                default="outer")
            private$..btnRes <- jmvcore::OptionAction$new(
                "btnRes",
                btnRes,
                default=FALSE)

            self$.addOption(private$..varBy)
            self$.addOption(private$..varAll)
            self$.addOption(private$..fleInp)
            self$.addOption(private$..fleChs)
            self$.addOption(private$..typMrg)
            self$.addOption(private$..btnRes)
        }),
    active = list(
        varBy = function() private$..varBy$value,
        varAll = function() private$..varAll$value,
        fleInp = function() private$..fleInp$value,
        fleChs = function() private$..fleChs$value,
        typMrg = function() private$..typMrg$value,
        btnRes = function() private$..btnRes$value),
    private = list(
        ..varBy = NA,
        ..varAll = NA,
        ..fleInp = NA,
        ..fleChs = NA,
        ..typMrg = NA,
        ..btnRes = NA)
)

jrmergecolsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        pvwDta = function() private$.items[["pvwDta"]],
        addInf = function() private$.items[["addInf"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Merge Columns")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                clearWith=list(
                    "varBy",
                    "varAll",
                    "fleInp",
                    "typMrg",
                    "btnRes")))
            self$add(jmvcore::Table$new(
                options=options,
                name="pvwDta",
                title="Data Preview",
                refs=list(
                    "jmvReadWrite"),
                clearWith=list(
                    "varBy",
                    "varAll",
                    "fleInp",
                    "typMrg"),
                rows=1,
                columns=list(
                    list(
                        `name`="fstCol", 
                        `title`=""))))
            self$add(jmvcore::Html$new(
                options=options,
                name="addInf",
                clearWith=NULL,
                content="<h2>Details</h2> <div style=\"text-align:justify\"> <p>There are <b>four different types of merging</b> operations:<br/><br/> 1) <b>Keeps All Cases (Rows)</b><br/>  keeps all cases (but if some input data sets did not contain that value of the matching variable, there might be missing values for variable from that data set).<br/> 2) <b>Keeps Only Cases Contained in All Merged Data Sets</b><br/> Keeps only those cases where a particular value of the matching variable was contained in all datasets.<br/> 3) <b>Keeps All Cases From the Currently Opened Data Set</b><br/> Keeps all rows/cases from the active data set (whereas cases that are only contained in the data sets defined under \"Data Set(s) to Add\" are dropped).<br/> 4) <b>Keeps All Cases From the Data Sets To Be Added</b><br/> Keeps all cases from the data sets defined under \"Data Set(s) to Add\" (whereas cases that are only contained in the active data set are dropped).</p><hr> <p>If there are variables with the same name in several of the input data sets, it will checked whether they contain the same content.<br/> If they are the same, only the first of these identical variables is kept (and the others are removed).<br/> If they are different, the name of the first of these variables is kept,  and a suffix with their position (_2, _3, etc.) will be added to the name of all other variables.</p></div>\n"))}))

jrmergecolsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReshape",
                name = "jrmergecols",
                version = c(1,0,0),
                options = options,
                results = jrmergecolsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Merge Columns
#'
#' 
#' @param data the data as a data frame
#' @param varBy .
#' @param varAll .
#' @param fleInp .
#' @param fleChs .
#' @param typMrg .
#' @param btnRes .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pvwDta} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$addInf} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pvwDta$asDF}
#'
#' \code{as.data.frame(results$pvwDta)}
#'
#' @export
jrmergecols <- function(
    data,
    varBy = NULL,
    varAll = NULL,
    fleInp = "",
    fleChs = "",
    typMrg = "outer",
    btnRes = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrmergecols requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varBy)) varBy <- jmvcore::resolveQuo(jmvcore::enquo(varBy))
    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varBy), varBy, NULL),
            `if`( ! missing(varAll), varAll, NULL))


    options <- jrmergecolsOptions$new(
        varBy = varBy,
        varAll = varAll,
        fleInp = fleInp,
        fleChs = fleChs,
        typMrg = typMrg,
        btnRes = btnRes)

    analysis <- jrmergecolsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

