
# This file is automatically generated, you probably don't want to edit this

jrmergecolsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varBy = NULL,
            varAll = NULL,
            fleInp = "",
            fleChs = NULL,
            fleRes = NULL,
            type = "outer",
            btnReshape = FALSE,
            showMergeReport = FALSE,
            nfiles = 0,
            jlog = FALSE, ...) {

            super$initialize(
                package="jReshape",
                name="jrmergecols",
                requiresData=TRUE,
                ...)

            private$..varBy <- jmvcore::OptionVariables$new(
                "varBy",
                varBy,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..fleInp <- jmvcore::OptionString$new(
                "fleInp",
                fleInp,
                default="")
            private$..fleChs <- jmvcore::OptionString$new(
                "fleChs",
                fleChs,
                hidden=TRUE)
            private$..fleRes <- jmvcore::OptionString$new(
                "fleRes",
                fleRes,
                hidden=TRUE)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "outer",
                    "inner",
                    "left",
                    "right"),
                default="outer")
            private$..btnReshape <- jmvcore::OptionAction$new(
                "btnReshape",
                btnReshape,
                hidden=TRUE,
                default=FALSE)
            private$..showMergeReport <- jmvcore::OptionBool$new(
                "showMergeReport",
                showMergeReport,
                default=FALSE)
            private$..nfiles <- jmvcore::OptionInteger$new(
                "nfiles",
                nfiles,
                hidden=TRUE,
                default=0)
            private$..jlog <- jmvcore::OptionBool$new(
                "jlog",
                jlog,
                hidden=TRUE,
                default=FALSE)

            self$.addOption(private$..varBy)
            self$.addOption(private$..varAll)
            self$.addOption(private$..fleInp)
            self$.addOption(private$..fleChs)
            self$.addOption(private$..fleRes)
            self$.addOption(private$..type)
            self$.addOption(private$..btnReshape)
            self$.addOption(private$..showMergeReport)
            self$.addOption(private$..nfiles)
            self$.addOption(private$..jlog)
        }),
    active = list(
        varBy = function() private$..varBy$value,
        varAll = function() private$..varAll$value,
        fleInp = function() private$..fleInp$value,
        fleChs = function() private$..fleChs$value,
        fleRes = function() private$..fleRes$value,
        type = function() private$..type$value,
        btnReshape = function() private$..btnReshape$value,
        showMergeReport = function() private$..showMergeReport$value,
        nfiles = function() private$..nfiles$value,
        jlog = function() private$..jlog$value),
    private = list(
        ..varBy = NA,
        ..varAll = NA,
        ..fleInp = NA,
        ..fleChs = NA,
        ..fleRes = NA,
        ..type = NA,
        ..btnReshape = NA,
        ..showMergeReport = NA,
        ..nfiles = NA,
        ..jlog = NA)
)

jrmergecolsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        info = function() private$.items[["info"]],
        features = function() private$.items[["features"]],
        showdata = function() private$.items[["showdata"]],
        mergeReport = function() private$.items[["mergeReport"]],
        modstyletabs = function() private$.items[["modstyletabs"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Merge Columns")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                title="Getting started",
                clearWith=list(
                    "fleInp",
                    "varBy",
                    "btnReshape")))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                clearWith=list(
                    "varBy",
                    "varAll",
                    "fleInp",
                    "type"),
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="Common Variables",
                clearWith=list(
                    "fleInp",
                    "varBy"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="lab", 
                        `title`="Type.x", 
                        `type`="text"),
                    list(
                        `name`="lab1", 
                        `title`="Type.y1", 
                        `type`="text"),
                    list(
                        `name`="lab2", 
                        `title`="Type.y2", 
                        `type`="text", 
                        `visible`="(nfiles >= 2)"),
                    list(
                        `name`="lab3", 
                        `title`="Type.y3", 
                        `type`="text", 
                        `visible`="(nfiles >= 3)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                clearWith=list(
                    "varBy",
                    "varAll",
                    "fleInp",
                    "type"),
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="mergeReport",
                title="",
                visible=FALSE,
                clearWith=list(
                    "varBy",
                    "varAll",
                    "fleInp",
                    "type"),
                content=""))
            self$add(jmvcore::Html$new(
                options=options,
                name="modstyletabs",
                visible=TRUE,
                clearWith=list(),
                content="<style> /* Hide the element with id \"modstyletabs\" if needed */ #modstyletabs { display: none; }\n/* Style for the table */ table {\n  width: 100%;\n  border-collapse: collapse;\n}\n/* Style for the table caption (title) */ caption {\n  font-family: Arial, sans-serif;\n  font-size: 1rem;    /* Using rem (0.875rem is equivalent a 14px if the root font-size is 16px) */\n  font-weight: bold;  /* Makes the text bold */\n  color: #3e6da9;     /* Sets the text color to jamovi blue */\n  margin-bottom: 8px; /* Optional: adds some spacing below the caption */\n}\n/* Style for table headers and cells */ th, td {\n  border: 1px solid #ddd;\n  padding: 8px;\n  font-family: Arial, sans-serif;\n  font-size: 0.75rem; /* For example, 0.75rem equals 12px if root font-size is 16px */\n}\n/* Style for column headers only */ th {\n  background-color: #3e6da9;    /* Jamovi blue for header background */\n  color: white;                 /* Text color for headers */\n  text-align: left;\n}\n/* Row styles */ tr:nth-child(even) {\n  background-color: #d6eaf8;\n} tr:nth-child(odd) {\n  background-color: #ffffff;\n} tr:hover {\n  background-color: #aed6f1;\n} </style>\n"))}))

jrmergecolsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReshape",
                name = "jrmergecols",
                version = c(1,0,0),
                options = options,
                results = jrmergecolsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Merge Columns
#'
#' 
#' @param data the data as a data frame
#' @param varBy .
#' @param varAll .
#' @param fleInp .
#' @param fleChs .
#' @param fleRes .
#' @param type .
#' @param btnReshape .
#' @param showMergeReport Enable this option to generate detailed information
#'   in HTML format
#' @param nfiles .
#' @param jlog .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mergeReport} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modstyletabs} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
jrmergecols <- function(
    data,
    varBy,
    varAll,
    fleInp = "",
    fleChs,
    fleRes,
    type = "outer",
    btnReshape = FALSE,
    showMergeReport = FALSE,
    nfiles = 0,
    jlog = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrmergecols requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varBy)) varBy <- jmvcore::resolveQuo(jmvcore::enquo(varBy))
    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varBy), varBy, NULL),
            `if`( ! missing(varAll), varAll, NULL))


    options <- jrmergecolsOptions$new(
        varBy = varBy,
        varAll = varAll,
        fleInp = fleInp,
        fleChs = fleChs,
        fleRes = fleRes,
        type = type,
        btnReshape = btnReshape,
        showMergeReport = showMergeReport,
        nfiles = nfiles,
        jlog = jlog)

    analysis <- jrmergecolsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

