
# This file is automatically generated, you probably don't want to edit this

jrmergecolsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varBy = NULL,
            varAll = NULL,
            fleInp = "",
            fleChs = NULL,
            fleRes = NULL,
            type = "outer",
            common = "both",
            btnReshape = FALSE, ...) {

            super$initialize(
                package="jReshape",
                name="jrmergecols",
                requiresData=TRUE,
                ...)

            private$..varBy <- jmvcore::OptionVariables$new(
                "varBy",
                varBy,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..varAll <- jmvcore::OptionVariables$new(
                "varAll",
                varAll,
                hidden=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..fleInp <- jmvcore::OptionString$new(
                "fleInp",
                fleInp,
                default="")
            private$..fleChs <- jmvcore::OptionString$new(
                "fleChs",
                fleChs,
                hidden=TRUE)
            private$..fleRes <- jmvcore::OptionString$new(
                "fleRes",
                fleRes,
                hidden=TRUE)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "outer",
                    "inner",
                    "left",
                    "right"),
                default="outer")
            private$..common <- jmvcore::OptionList$new(
                "common",
                common,
                options=list(
                    "both",
                    "left",
                    "right"),
                default="both")
            private$..btnReshape <- jmvcore::OptionAction$new(
                "btnReshape",
                btnReshape,
                hidden=TRUE,
                default=FALSE)

            self$.addOption(private$..varBy)
            self$.addOption(private$..varAll)
            self$.addOption(private$..fleInp)
            self$.addOption(private$..fleChs)
            self$.addOption(private$..fleRes)
            self$.addOption(private$..type)
            self$.addOption(private$..common)
            self$.addOption(private$..btnReshape)
        }),
    active = list(
        varBy = function() private$..varBy$value,
        varAll = function() private$..varAll$value,
        fleInp = function() private$..fleInp$value,
        fleChs = function() private$..fleChs$value,
        fleRes = function() private$..fleRes$value,
        type = function() private$..type$value,
        common = function() private$..common$value,
        btnReshape = function() private$..btnReshape$value),
    private = list(
        ..varBy = NA,
        ..varAll = NA,
        ..fleInp = NA,
        ..fleChs = NA,
        ..fleRes = NA,
        ..type = NA,
        ..common = NA,
        ..btnReshape = NA)
)

jrmergecolsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        info = function() private$.items[["info"]],
        features = function() private$.items[["features"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Merge Columns")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                title="Getting started",
                clearWith=list(
                    "fleInp",
                    "varBy",
                    "btnReshape")))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                clearWith=list(
                    "fleInp",
                    "varBy",
                    "common",
                    "type"),
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="Common Variables",
                clearWith=list(
                    "fleInp",
                    "varBy"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="lab1", 
                        `title`="Type.x", 
                        `type`="text"),
                    list(
                        `name`="lab2", 
                        `title`="Type.y", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                clearWith=list(
                    "fleInp",
                    "varBy",
                    "type",
                    "common"),
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

jrmergecolsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrmergecolsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReshape",
                name = "jrmergecols",
                version = c(1,0,0),
                options = options,
                results = jrmergecolsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Merge Columns
#'
#' 
#' @param data the data as a data frame
#' @param varBy .
#' @param varAll .
#' @param fleInp .
#' @param fleChs .
#' @param fleRes .
#' @param type .
#' @param common .
#' @param btnReshape .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
jrmergecols <- function(
    data,
    varBy,
    varAll,
    fleInp = "",
    fleChs,
    fleRes,
    type = "outer",
    common = "both",
    btnReshape = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrmergecols requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varBy)) varBy <- jmvcore::resolveQuo(jmvcore::enquo(varBy))
    if ( ! missing(varAll)) varAll <- jmvcore::resolveQuo(jmvcore::enquo(varAll))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varBy), varBy, NULL),
            `if`( ! missing(varAll), varAll, NULL))


    options <- jrmergecolsOptions$new(
        varBy = varBy,
        varAll = varAll,
        fleInp = fleInp,
        fleChs = fleChs,
        fleRes = fleRes,
        type = type,
        common = common,
        btnReshape = btnReshape)

    analysis <- jrmergecolsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

