
# This file is automatically generated, you probably don't want to edit this

mergeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mergeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            filename = NULL,
            covs = NULL,
            index = NULL,
            reshape = NULL, ...) {

            super$initialize(
                package="jReshape",
                name="merge",
                requiresData=TRUE,
                ...)

            private$..filename <- jmvcore::OptionString$new(
                "filename",
                filename)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs)
            private$..index <- jmvcore::OptionVariables$new(
                "index",
                index)
            private$..reshape <- jmvcore::OptionAction$new(
                "reshape",
                reshape)

            self$.addOption(private$..filename)
            self$.addOption(private$..covs)
            self$.addOption(private$..index)
            self$.addOption(private$..reshape)
        }),
    active = list(
        filename = function() private$..filename$value,
        covs = function() private$..covs$value,
        index = function() private$..index$value,
        reshape = function() private$..reshape$value),
    private = list(
        ..filename = NA,
        ..covs = NA,
        ..index = NA,
        ..reshape = NA)
)

mergeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mergeResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        info = function() private$.items[["info"]],
        fileinfo = function() private$.items[["fileinfo"]],
        exfileinfo = function() private$.items[["exfileinfo"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Merge")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                title="Getting started"))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                clearWith=list(
                    "rowstocols",
                    "index",
                    "id",
                    "covs"),
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fileinfo",
                title="Selected variables info",
                clearWith=list(
                    "index",
                    "covs",
                    "nocovs",
                    "filename"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="dataType", 
                        `title`="Data Type", 
                        `type`="text"),
                    list(
                        `name`="measureType", 
                        `title`="Measure Type", 
                        `type`="text"),
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="text"),
                    list(
                        `name`="description", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="exfileinfo",
                title="External file info",
                clearWith=list(
                    "index",
                    "covs",
                    "nocovs",
                    "filename"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="dataType", 
                        `title`="Data Type", 
                        `type`="text"),
                    list(
                        `name`="measureType", 
                        `title`="Measure Type", 
                        `type`="text"),
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="text"),
                    list(
                        `name`="description", 
                        `title`="Description", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                clearWith=list(
                    "rowstocols",
                    "index",
                    "id",
                    "covs"),
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

mergeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mergeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReshape",
                name = "merge",
                version = c(1,0,0),
                options = options,
                results = mergeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Merge
#'
#' 
#' @param data .
#' @param filename .
#' @param covs .
#' @param index .
#' @param reshape .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fileinfo} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$exfileinfo} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
merge <- function(
    data,
    filename,
    covs,
    index,
    reshape) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("merge requires jmvcore to be installed (restart may be required)")

    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(index)) index <- jmvcore::resolveQuo(jmvcore::enquo(index))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(index), index, NULL))


    options <- mergeOptions$new(
        filename = filename,
        covs = covs,
        index = index,
        reshape = reshape)

    analysis <- mergeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

