
# This file is automatically generated, you probably don't want to edit this

simple2longOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simple2longOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "mode1",
            sim_colstorows = NULL,
            sim_covs = NULL,
            sim_index = "index",
            sim_dep = "y",
            open = TRUE,
            button = NULL,
            create = FALSE,
            toggle = FALSE,
            comp_colstorows = list(
                list(label="long_y", vars=list())),
            comp_index = list(
                list(var="index1", levels=0)), ...) {

            super$initialize(
                package="jReshape",
                name="simple2long",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "mode1",
                    "mode2"),
                default="mode1")
            private$..sim_colstorows <- jmvcore::OptionVariables$new(
                "sim_colstorows",
                sim_colstorows)
            private$..sim_covs <- jmvcore::OptionVariables$new(
                "sim_covs",
                sim_covs)
            private$..sim_index <- jmvcore::OptionString$new(
                "sim_index",
                sim_index,
                default="index")
            private$..sim_dep <- jmvcore::OptionString$new(
                "sim_dep",
                sim_dep,
                default="y")
            private$..open <- jmvcore::OptionBool$new(
                "open",
                open,
                default=TRUE)
            private$..button <- jmvcore::OptionString$new(
                "button",
                button,
                hidden=TRUE)
            private$..create <- jmvcore::OptionBool$new(
                "create",
                create,
                default=FALSE,
                hidden=TRUE)
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                default=FALSE,
                hidden=TRUE)
            private$..comp_colstorows <- jmvcore::OptionArray$new(
                "comp_colstorows",
                comp_colstorows,
                default=list(
                    list(label="long_y", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "comp_colstorows",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL))))
            private$..comp_index <- jmvcore::OptionArray$new(
                "comp_index",
                comp_index,
                default=list(
                    list(var="index1", levels=0)),
                template=jmvcore::OptionGroup$new(
                    "comp_index",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "var",
                            NULL),
                        jmvcore::OptionInteger$new(
                            "levels",
                            NULL))))

            self$.addOption(private$..mode)
            self$.addOption(private$..sim_colstorows)
            self$.addOption(private$..sim_covs)
            self$.addOption(private$..sim_index)
            self$.addOption(private$..sim_dep)
            self$.addOption(private$..open)
            self$.addOption(private$..button)
            self$.addOption(private$..create)
            self$.addOption(private$..toggle)
            self$.addOption(private$..comp_colstorows)
            self$.addOption(private$..comp_index)
        }),
    active = list(
        mode = function() private$..mode$value,
        sim_colstorows = function() private$..sim_colstorows$value,
        sim_covs = function() private$..sim_covs$value,
        sim_index = function() private$..sim_index$value,
        sim_dep = function() private$..sim_dep$value,
        open = function() private$..open$value,
        button = function() private$..button$value,
        create = function() private$..create$value,
        toggle = function() private$..toggle$value,
        comp_colstorows = function() private$..comp_colstorows$value,
        comp_index = function() private$..comp_index$value),
    private = list(
        ..mode = NA,
        ..sim_colstorows = NA,
        ..sim_covs = NA,
        ..sim_index = NA,
        ..sim_dep = NA,
        ..open = NA,
        ..button = NA,
        ..create = NA,
        ..toggle = NA,
        ..comp_colstorows = NA,
        ..comp_index = NA)
)

simple2longResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simple2longResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        info = function() private$.items[["info"]],
        features = function() private$.items[["features"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Wide to Long format")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                title="Getting started"))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                clearWith=NULL,
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="Repeated measures levels",
                columns=list(
                    list(
                        `name`="Var1", 
                        `title`="rmlevels", 
                        `type`="text"),
                    list(
                        `name`="Freq", 
                        `title`="Freq", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="showdata",
                title="Data Preview",
                columns=list(
                    list(
                        `name`="row", 
                        `title`="Rows", 
                        `type`="integer"))))}))

simple2longBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simple2longBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReshape",
                name = "simple2long",
                version = c(1,0,0),
                options = options,
                results = simple2longResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Wide to Long format (simple)
#'
#' 
#' @param data .
#' @param mode .
#' @param sim_colstorows .
#' @param sim_covs .
#' @param sim_index .
#' @param sim_dep .
#' @param open .
#' @param button .
#' @param create .
#' @param toggle .
#' @param comp_colstorows .
#' @param comp_index .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
simple2long <- function(
    data,
    mode = "mode1",
    sim_colstorows,
    sim_covs,
    sim_index = "index",
    sim_dep = "y",
    open = TRUE,
    button,
    create = FALSE,
    toggle = FALSE,
    comp_colstorows = list(
                list(label="long_y", vars=list())),
    comp_index = list(
                list(var="index1", levels=0))) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("simple2long requires jmvcore to be installed (restart may be required)")

    if ( ! missing(sim_colstorows)) sim_colstorows <- jmvcore::resolveQuo(jmvcore::enquo(sim_colstorows))
    if ( ! missing(sim_covs)) sim_covs <- jmvcore::resolveQuo(jmvcore::enquo(sim_covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(sim_colstorows), sim_colstorows, NULL),
            `if`( ! missing(sim_covs), sim_covs, NULL))


    options <- simple2longOptions$new(
        mode = mode,
        sim_colstorows = sim_colstorows,
        sim_covs = sim_covs,
        sim_index = sim_index,
        sim_dep = sim_dep,
        open = open,
        button = button,
        create = create,
        toggle = toggle,
        comp_colstorows = comp_colstorows,
        comp_index = comp_index)

    analysis <- simple2longClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

