
# This file is automatically generated, you probably don't want to edit this

simple2longOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simple2longOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            colstorows = NULL,
            covs = NULL,
            rmlevels = "time",
            dep = "y",
            filename = NULL,
            save = FALSE, ...) {

            super$initialize(
                package="jReshape",
                name="simple2long",
                requiresData=TRUE,
                ...)

            private$..colstorows <- jmvcore::OptionVariables$new(
                "colstorows",
                colstorows)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs)
            private$..rmlevels <- jmvcore::OptionString$new(
                "rmlevels",
                rmlevels,
                default="time")
            private$..dep <- jmvcore::OptionString$new(
                "dep",
                dep,
                default="y")
            private$..filename <- jmvcore::OptionString$new(
                "filename",
                filename)
            private$..save <- jmvcore::OptionBool$new(
                "save",
                save,
                default=FALSE)

            self$.addOption(private$..colstorows)
            self$.addOption(private$..covs)
            self$.addOption(private$..rmlevels)
            self$.addOption(private$..dep)
            self$.addOption(private$..filename)
            self$.addOption(private$..save)
        }),
    active = list(
        colstorows = function() private$..colstorows$value,
        covs = function() private$..covs$value,
        rmlevels = function() private$..rmlevels$value,
        dep = function() private$..dep$value,
        filename = function() private$..filename$value,
        save = function() private$..save$value),
    private = list(
        ..colstorows = NA,
        ..covs = NA,
        ..rmlevels = NA,
        ..dep = NA,
        ..filename = NA,
        ..save = NA)
)

simple2longResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simple2longResults",
    inherit = jmvcore::Group,
    active = list(
        help = function() private$.items[["help"]],
        save = function() private$.items[["save"]],
        info = function() private$.items[["info"]],
        features = function() private$.items[["features"]],
        showdata = function() private$.items[["showdata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="jReshape: Wide to Long format")
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                title="Getting started"))
            self$add(jmvcore::Table$new(
                options=options,
                name="save",
                title="The new data file has been saved as",
                visible="(save)",
                columns=list(
                    list(
                        `name`="text", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="info", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Info Table",
                columns=list(
                    list(
                        `name`="text", 
                        `title`="Info", 
                        `type`="text"),
                    list(
                        `name`="var", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="features",
                title="Repeated measures levels",
                columns=list(
                    list(
                        `name`="Var1", 
                        `title`="rmlevels", 
                        `type`="text"),
                    list(
                        `name`="Freq", 
                        `title`="Freq", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="showdata",
                title="Data Preview"))}))

simple2longBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simple2longBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReshape",
                name = "simple2long",
                version = c(1,0,0),
                options = options,
                results = simple2longResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' jReshape: Wide to Long format
#'
#' 
#' @param data .
#' @param colstorows .
#' @param covs .
#' @param rmlevels .
#' @param dep .
#' @param filename .
#' @param save .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$save} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$features} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$showdata} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$save$asDF}
#'
#' \code{as.data.frame(results$save)}
#'
#' @export
simple2long <- function(
    data,
    colstorows,
    covs,
    rmlevels = "time",
    dep = "y",
    filename,
    save = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("simple2long requires jmvcore to be installed (restart may be required)")

    if ( ! missing(colstorows)) colstorows <- jmvcore::resolveQuo(jmvcore::enquo(colstorows))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(colstorows), colstorows, NULL),
            `if`( ! missing(covs), covs, NULL))


    options <- simple2longOptions$new(
        colstorows = colstorows,
        covs = covs,
        rmlevels = rmlevels,
        dep = dep,
        filename = filename,
        save = save)

    analysis <- simple2longClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

